# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdU7PqiT834qFkaPiKHBUzBQP-Gwf49s
"""

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def extract_frames_from_gif(gif_path):
    gif = Image.open(gif_path)
    frames = []
    for frame_idx in range(gif.n_frames):
        gif.seek(frame_idx)
        frame = np.array(gif.convert('RGB'))
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
        frames.append(frame)
    return frames

def rgb_to_grayscale(img):
    if img is None:
        raise ValueError("Input image cannot be None")
    return (0.2989 * img[:,:,2] + 0.5870 * img[:,:,1] + 0.1140 * img[:,:,0]).astype(np.uint8)

def fast_block_matching(left, right, block_size=9, max_disparity=64):
    h, w = left.shape
    half_block = block_size // 2
    disparity_map = np.zeros((h, w), dtype=np.float32)

    for y in range(half_block, h - half_block):
        for x in range(half_block, w - half_block):
            left_block = left[y-half_block:y+half_block+1, x-half_block:x+half_block+1]

            best_disparity = 0
            best_cost = float('inf')

            min_x_right = max(half_block, x - max_disparity)

            for x_right in range(min_x_right, x - half_block + 1):
                right_block = right[y-half_block:y+half_block+1, x_right-half_block:x_right+half_block+1]

                if right_block.shape == left_block.shape:
                    diff = left_block.astype(np.int16) - right_block.astype(np.int16)
                    cost = np.sum(np.abs(diff))

                    if cost < best_cost:
                        best_cost = cost
                        best_disparity = x - x_right

            disparity_map[y, x] = best_disparity

    return disparity_map

def normalize_disparity(disparity):
    valid = disparity[disparity > 0]

    if len(valid) > 0:
        min_val = np.percentile(valid, 2)
        max_val = np.percentile(valid, 98)

        disparity = np.clip(disparity, min_val, max_val)
        normalized = ((disparity - min_val) / (max_val - min_val + 1e-6)) * 255
    else:
        normalized = np.zeros_like(disparity)

    return normalized.astype(np.uint8)

def apply_jet_colormap(depth_map):
    h, w = depth_map.shape
    colored = np.zeros((h, w, 3), dtype=np.uint8)

    for y in range(h):
        for x in range(w):
            v = depth_map[y, x] / 255.0

            if v <= 0.125:
                r, g, b = 0, 0, 0.5 + v * 4
            elif v <= 0.375:
                r, g, b = 0, v * 4 - 0.5, 1
            elif v <= 0.625:
                r, g, b = v * 4 - 1.5, 1, 1 - (v * 4 - 1.5)
            elif v <= 0.875:
                r, g, b = 1, 1 - (v * 4 - 2.5), 0
            else:
                r, g, b = 1 - (v * 4 - 3.5), 0, 0

            colored[y, x] = [int(b * 255), int(g * 255), int(r * 255)]

    return colored

def compute_depth_from_scratch(left, right):
    left_gray = rgb_to_grayscale(left)
    right_gray = rgb_to_grayscale(right)

    disparity = fast_block_matching(left_gray, right_gray)
    depth_map = normalize_disparity(disparity)
    colored_depth = apply_jet_colormap(depth_map)

    return depth_map, colored_depth

def depth_from_two_images(left_path, right_path):
    left = cv2.imread(left_path)
    right = cv2.imread(right_path)

    if left is None:
        raise FileNotFoundError(f"Left image not found: {left_path}")
    if right is None:
        raise FileNotFoundError(f"Right image not found: {right_path}")

    depth_map, colored_depth = compute_depth_from_scratch(left, right)

    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(cv2.cvtColor(left, cv2.COLOR_BGR2RGB))
    plt.title("Left Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(depth_map, cmap="gray")
    plt.title("Depth Map")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(colored_depth)
    plt.title("Colored Depth")
    plt.axis("off")

    plt.show()

    return depth_map, colored_depth